---
name: Checks

on: [push] # this is the tirgger

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        user: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        user: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" #command that runs the unit test on our project
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8" # if any of the steps fails the job running fails
